// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr_Emu1o9oPZrfUn3ofrTwb3MZ0hpzD68',
    appId: '1:784730084385:web:3867eb8d6dc64980713f60',
    messagingSenderId: '784730084385',
    projectId: 'oneupnoobs-9ee91',
    authDomain: 'oneupnoobs-9ee91.firebaseapp.com',
    storageBucket: 'oneupnoobs-9ee91.appspot.com',
    measurementId: 'G-2F2QT7JEX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3fZM3PJ3PYqZEsqbRHK5-6n2Mxp_g5QM',
    appId: '1:784730084385:android:3dabc1762ab71efc713f60',
    messagingSenderId: '784730084385',
    projectId: 'oneupnoobs-9ee91',
    storageBucket: 'oneupnoobs-9ee91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpgQLaw1lF8QsxY-TTlC3cKjq0MnmmVgI',
    appId: '1:784730084385:ios:4dbbd322afa3e74e713f60',
    messagingSenderId: '784730084385',
    projectId: 'oneupnoobs-9ee91',
    storageBucket: 'oneupnoobs-9ee91.appspot.com',
    iosBundleId: 'com.example.oneupNoobs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpgQLaw1lF8QsxY-TTlC3cKjq0MnmmVgI',
    appId: '1:784730084385:ios:4dbbd322afa3e74e713f60',
    messagingSenderId: '784730084385',
    projectId: 'oneupnoobs-9ee91',
    storageBucket: 'oneupnoobs-9ee91.appspot.com',
    iosBundleId: 'com.example.oneupNoobs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr_Emu1o9oPZrfUn3ofrTwb3MZ0hpzD68',
    appId: '1:784730084385:web:1f4ed2dc80eeae6b713f60',
    messagingSenderId: '784730084385',
    projectId: 'oneupnoobs-9ee91',
    authDomain: 'oneupnoobs-9ee91.firebaseapp.com',
    storageBucket: 'oneupnoobs-9ee91.appspot.com',
    measurementId: 'G-LXYD803NP7',
  );
}
