// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwR2aKXV2nKRiVJ8R6jpJMUfssEHMP2bA',
    appId: '1:523847778061:web:db084b6ae95e87f1fafa44',
    messagingSenderId: '523847778061',
    projectId: 'oneupnoobs-59d99',
    authDomain: 'oneupnoobs-59d99.firebaseapp.com',
    databaseURL: 'https://oneupnoobs-59d99-default-rtdb.firebaseio.com',
    storageBucket: 'oneupnoobs-59d99.appspot.com',
    measurementId: 'G-QCCL14RFGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMVhRP6RaF_UANGLjQk4Heypzfp17XVj4',
    appId: '1:523847778061:android:d1f1ada960338546fafa44',
    messagingSenderId: '523847778061',
    projectId: 'oneupnoobs-59d99',
    databaseURL: 'https://oneupnoobs-59d99-default-rtdb.firebaseio.com',
    storageBucket: 'oneupnoobs-59d99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCinZqK3Fzrlf_WRpYvoBxZOdkszEbxx_g',
    appId: '1:523847778061:ios:42ed51741de9629afafa44',
    messagingSenderId: '523847778061',
    projectId: 'oneupnoobs-59d99',
    databaseURL: 'https://oneupnoobs-59d99-default-rtdb.firebaseio.com',
    storageBucket: 'oneupnoobs-59d99.appspot.com',
    iosClientId: '523847778061-rj5lo7vg9e1jbl2kclp2epmoil91vvjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneupNoobs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCinZqK3Fzrlf_WRpYvoBxZOdkszEbxx_g',
    appId: '1:523847778061:ios:42ed51741de9629afafa44',
    messagingSenderId: '523847778061',
    projectId: 'oneupnoobs-59d99',
    databaseURL: 'https://oneupnoobs-59d99-default-rtdb.firebaseio.com',
    storageBucket: 'oneupnoobs-59d99.appspot.com',
    iosClientId: '523847778061-rj5lo7vg9e1jbl2kclp2epmoil91vvjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneupNoobs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwR2aKXV2nKRiVJ8R6jpJMUfssEHMP2bA',
    appId: '1:523847778061:web:d7d56df7c2a65a58fafa44',
    messagingSenderId: '523847778061',
    projectId: 'oneupnoobs-59d99',
    authDomain: 'oneupnoobs-59d99.firebaseapp.com',
    databaseURL: 'https://oneupnoobs-59d99-default-rtdb.firebaseio.com',
    storageBucket: 'oneupnoobs-59d99.appspot.com',
    measurementId: 'G-L8MR5QR6QJ',
  );

}